# Site settings
baseurl = "https://ctmain.co.uk"
languageCode = "en-us"
title = "C.T. MAIN | Artist"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-140212719-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

enableRobotsTXT = "true"

[params]
    # Meta
    title = "C.T. MAIN"
    #subtitle = ""
    author = "Daniel Fraser"
    description = "C. T. Main is a recently discovered “outsider artist” who grew up in Wales and the North East of England. Through his unique visual language, C.T. introduces us, with acerbic wit, to a ghastly yet beguiling panoply of the living and the dead; mortal and Minotaur."
    #keywords = ""
    image = "https://ctmain.co.uk/images/websiteImage.jpg"

    # Body background color
    # bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Enquire"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']

[taxonomies]
