# Site settings
baseurl = "/"
languageCode = "en-us"
title = "CT MAIN"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    #title = "CT MAIN"
    #subtitle = "A kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on."
    title = "CT MAIN"
    author = "Daniel Fraser"
    #description = "Hugrid - grid theme for Hugo with an expanding image preview."
    #keywords = "Hugo, Hugo theme, grid theme, portfolio, bookmarks, collection, contacts"

    # Body background color
    # bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Enquire"

    # Footer text
    footertext = "Made by [Codrops](http://tympanus.net/codrops/2013/03/19/thumbnail-grid-with-expanding-preview/), [Hugo](http://gohugo.io) and [me](https://github.com/aerohub)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
